# Generated by Django 4.2.5 on 2023-10-12 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='padrinho',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='children',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
