# Generated by Django 4.2.6 on 2023-10-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='doacoes',
            field=models.ManyToManyField(blank=True, default=None, to='lottusApp.doacao'),
        ),
    ]
