# Generated by Django 4.2.5 on 2023-10-13 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottusApp', '0002_children_padrinho_alter_children_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='padrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.IntegerField()),
                ('crianca', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lottusApp.children')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
