# Generated by Django 4.2.5 on 2023-10-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0003_alter_children_padrinho_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
