# Generated by Django 4.2.6 on 2023-11-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0004_itemprestacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPrestacao',
            new_name='Valor',
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.ManyToManyField(blank=True, default=None, to='lottusApp.valor')),
            ],
        ),
    ]
