# Generated by Django 4.2.5 on 2023-10-13 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0004_perfil_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='crianca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lottusApp.children'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
    ]
