# Generated by Django 4.2.5 on 2023-10-13 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0005_alter_perfil_crianca_alter_perfil_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lottusApp.children'),
        ),
    ]
