# Generated by Django 4.2.5 on 2023-10-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0006_alter_perfil_crianca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='crianca',
        ),
    ]
