# Generated by Django 4.2.6 on 2023-10-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0007_remove_perfil_crianca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
    ]
