# Generated by Django 4.2.6 on 2023-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0011_perfil_crianca_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='foto_url',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
