# Generated by Django 4.2.6 on 2023-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0012_children_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='foto_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
