# Generated by Django 4.2.6 on 2023-10-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0013_alter_children_foto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='foto_url',
        ),
    ]
