# Generated by Django 4.2.6 on 2023-10-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0014_remove_children_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='children',
            name='atividades',
            field=models.ManyToManyField(to='lottusApp.atividade'),
        ),
    ]
