# Generated by Django 4.2.6 on 2023-10-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottusApp', '0015_atividade_children_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='local',
            field=models.CharField(default='Sem informação', max_length=512),
        ),
        migrations.AlterField(
            model_name='children',
            name='atividades',
            field=models.ManyToManyField(blank=True, default=None, to='lottusApp.atividade'),
        ),
    ]
